/**
 * LangGraph Agent State — shared state schema for the 6-agent pipeline
 * Agents: CreativeAssembly, ContextEvaluation, GenerativeOutput,
 *         ComplianceAuditor, IdentityResolution, PerformanceMonitor
 */

import { Annotation } from '@langchain/langgraph';

// ---------------------------------------------------------------------------
// Message type for agent communication
// ---------------------------------------------------------------------------

export interface AgentMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
  agentName?: string;
  timestamp?: number;
}

// ---------------------------------------------------------------------------
// Campaign brief passed into the pipeline
// ---------------------------------------------------------------------------

export interface CampaignBriefInput {
  campaignId: string;
  campaignName: string;
  platform: 'GOOGLE' | 'META';
  objective: 'LEAD_GEN' | 'CONVERSIONS' | 'AWARENESS' | 'TRAFFIC';
  targetAudience: string;
  product: string;      // e.g. "AI Workshop — 3-day intensive"
  usp: string;          // Unique Selling Proposition
  budget: number;       // INR paisa
  brandVoice: string;   // e.g. "Professional, authoritative, inspiring"
  cta: string;          // e.g. "Register Now", "Book Your Seat"
  landingPageUrl?: string;
}

// ---------------------------------------------------------------------------
// Creative variants produced by GenerativeOutput agent
// ---------------------------------------------------------------------------

export interface CreativeVariant {
  headline: string;
  description: string;
  imagePrompt?: string;    // Prompt for image generation
  videoPrompt?: string;    // Prompt for video generation
  generativeModel?: string; // Which model to use: 'veo3' | 'sora2' | 'runway' etc.
  platform: 'GOOGLE' | 'META';
  format: 'IMAGE' | 'VIDEO' | 'CAROUSEL' | 'RSA' | 'RESPONSIVE_DISPLAY';
}

// ---------------------------------------------------------------------------
// Compliance result from ComplianceAuditor agent
// ---------------------------------------------------------------------------

export interface ComplianceResult {
  variantIndex: number;
  compliant: boolean;
  score: number;        // 0–1
  violations: string[];
  suggestions: string[];
  approvedForDeployment: boolean; // score >= 0.85
}

// ---------------------------------------------------------------------------
// Performance insights from PerformanceMonitor agent
// ---------------------------------------------------------------------------

export interface PerformanceInsights {
  avgRoas: number;
  ctr: number;
  cpl: number;
  trend: 'UP' | 'DOWN' | 'STABLE';
  anomalies: string[];
  recommendations: string[];
}

// ---------------------------------------------------------------------------
// LangGraph State Annotation
// Channels use reducer functions to merge updates from parallel nodes
// ---------------------------------------------------------------------------

export const AdTechAgentStateAnnotation = Annotation.Root({
  // Input
  messages: Annotation<AgentMessage[]>({
    reducer: (existing, update) => [...existing, ...update],
    default: () => [],
  }),
  brief: Annotation<CampaignBriefInput | null>({
    reducer: (_existing, update) => update,
    default: () => null,
  }),

  // Context gathered by ContextEvaluation agent
  audienceContext: Annotation<string>({
    reducer: (_existing, update) => update,
    default: () => '',
  }),
  competitorInsights: Annotation<string>({
    reducer: (_existing, update) => update,
    default: () => '',
  }),
  platformBestPractices: Annotation<string>({
    reducer: (_existing, update) => update,
    default: () => '',
  }),

  // Creatives generated by CreativeAssembly + GenerativeOutput agents
  creativeVariants: Annotation<CreativeVariant[]>({
    reducer: (_existing, update) => update,
    default: () => [],
  }),

  // Compliance results from ComplianceAuditor agent
  complianceResults: Annotation<ComplianceResult[]>({
    reducer: (_existing, update) => update,
    default: () => [],
  }),

  // Approved variants after compliance filtering
  approvedVariants: Annotation<CreativeVariant[]>({
    reducer: (_existing, update) => update,
    default: () => [],
  }),

  // Performance insights from PerformanceMonitor agent
  performanceInsights: Annotation<PerformanceInsights | null>({
    reducer: (_existing, update) => update,
    default: () => null,
  }),

  // Identity resolution output
  resolvedLeadIds: Annotation<string[]>({
    reducer: (existing, update) => [...new Set([...existing, ...update])],
    default: () => [],
  }),

  // Pipeline control
  currentAgent: Annotation<string>({
    reducer: (_existing, update) => update,
    default: () => '',
  }),
  errors: Annotation<string[]>({
    reducer: (existing, update) => [...existing, ...update],
    default: () => [],
  }),
  completed: Annotation<boolean>({
    reducer: (_existing, update) => update,
    default: () => false,
  }),

  // Final output
  agentLogId: Annotation<string | null>({
    reducer: (_existing, update) => update,
    default: () => null,
  }),
});

export type AdTechAgentState = typeof AdTechAgentStateAnnotation.State;
